---
name: Test

'on':
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Cache Rust toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-fmt-${{ hashFiles('rust-toolchain.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-fmt-

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Format
        run: cargo fmt --all -- --check

  lint:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-clippy-
            ${{ runner.os }}-cargo-

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-check-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-check-
            ${{ runner.os }}-cargo-

      - uses: dtolnay/rust-toolchain@stable

      - name: Check
        run: cargo check

  test:
    name: Test (PostgreSQL ${{ matrix.postgres }})
    runs-on: ubuntu-latest
    needs:
      - format
      - lint
      - check

    strategy:
      fail-fast: false
      matrix:
        postgres:
          - 16
          - 17
          - 18

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v5

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-pg${{ matrix.postgres }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-test-pg${{ matrix.postgres }}-
            ${{ runner.os }}-cargo-test-
            ${{ runner.os }}-cargo-

      - uses: dtolnay/rust-toolchain@stable

      - name: Wait for PostgreSQL
        run: |
          timeout 30 bash -c 'until pg_isready -h localhost -p 5432 -U postgres; do sleep 1; done'
          echo "PostgreSQL ${{ matrix.postgres }} is ready!"

      - name: Show PostgreSQL version
        run: |
          psql -h localhost -U postgres -d postgres -c "SELECT version();"

      - name: Install and configure pg_stat_statements extension
        run: |
          # Configure shared_preload_libraries (requires restart)
          psql -h localhost -U postgres -d postgres -c "ALTER SYSTEM SET shared_preload_libraries = 'pg_stat_statements';"
          
          # Restart PostgreSQL container to load pg_stat_statements
          docker ps -a
          CONTAINER_ID=$(docker ps --filter "ancestor=postgres:${{ matrix.postgres }}" --format "{{.ID}}")
          echo "Restarting container $CONTAINER_ID"
          docker restart $CONTAINER_ID
          
          # Wait for PostgreSQL to be ready again
          sleep 5
          timeout 30 bash -c 'until pg_isready -h localhost -p 5432 -U postgres; do sleep 1; done'
          
          # Now set pg_stat_statements config (extension is preloaded)
          psql -h localhost -U postgres -d postgres -c "ALTER SYSTEM SET pg_stat_statements.track = 'all';"
          
          # Reload configuration
          psql -h localhost -U postgres -d postgres -c "SELECT pg_reload_conf();"
          
          # Enable pg_stat_statements extension
          psql -h localhost -U postgres -d postgres -c "CREATE EXTENSION IF NOT EXISTS pg_stat_statements;"
          
          # Verify extension is loaded
          psql -h localhost -U postgres -d postgres -c "SELECT extname, extversion FROM pg_extension WHERE extname = 'pg_stat_statements';"
          
          # Generate some test queries to populate pg_stat_statements
          psql -h localhost -U postgres -d postgres -c "SELECT 1;"
          psql -h localhost -U postgres -d postgres -c "SELECT current_timestamp;"
          psql -h localhost -U postgres -d postgres -c "SELECT COUNT(*) FROM pg_stat_statements;"

      - name: Run tests
        env:
          PG_EXPORTER_DSN: postgresql://postgres:postgres@localhost:5432/postgres
        run: cargo test
